# https://docs.docker.com/compose/gettingstarted/
# https://hackmd.io/@jpshafto/SJnFqs-Kd
# https://stackoverflow.com/questions/42216017/docker-compose-restart-policy

version: '3.8'

#-------------------------------------------------------------------------------
# https://kinsta.com/blog/docker-compose-volumes/

volumes:
  volume-wordpress:
    name: volume-wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/ppaquet/data/volume-wordpress
      o: bind

  volume-mariadb:
    name: volume-mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/ppaquet/data/volume-mariadb
      o: bind

# ---------------------------------------------------------------------------- #
# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects

networks:
  inception:
    name: inception
    driver: bridge
    # IP address management.
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/16"
          gateway: "192.168.0.1"

# ---------------------------------------------------------------------------- #

services:

  nginx:
    build:
      # Where the Dockerfile is located.
      context: ./requirements/nginx/
      # Dockerfile name *not required if already named 'Dockerfile'.
      dockerfile: Dockerfile
    # Custom name for the image being built.
    image: nginx-build:inception
    container_name: nginx
    ports:
      - "8080:80"
    restart: on-failure:5
    volumes:
      - volume-wordpress:/home/
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress-build:inception
    container_name: wordpress
    expose:
      - "9000"
    restart: on-failure:5
    volumes:
      - volume-wordpress:/usr/
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb-build:inception
    container_name: mariadb
    expose:
      - "3306"
    restart: on-failure:5
    volumes:
      - volume-mariadb:/tmp/
    networks:
      - inception
