# https://docs.docker.com/compose/gettingstarted/
# https://hackmd.io/@jpshafto/SJnFqs-Kd
# https://stackoverflow.com/questions/42216017/docker-compose-restart-policy

#-------------------------------------------------------------------------------
# https://kinsta.com/blog/docker-compose-volumes/

volumes:
  volume-wordpress:
    name: volume-wordpress
    driver: local
    driver_opts:
      type: none
      device: ~/data/volume-wordpress
      o: bind

  volume-mariadb:
    name: volume-mariadb
    driver: local
    driver_opts:
      type: none
      device: ~/data/volume-mariadb
      o: bind

# ---------------------------------------------------------------------------- #
# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects

networks:
  inception:
    # Prevents that directory name be append to the network's name
    # (when executing 'docker-compose' without specifying -f <path>)
    name: inception
    driver: bridge
    # IP Address Management.
    ipam:
      driver: default
      config:
        - subnet: ${INCEPTION_SUBNET}
          gateway: ${INCEPTION_GATEWAY}

# ---------------------------------------------------------------------------- #
# https://docs.docker.com/compose/use-secrets/

secrets:
  db_name:
    file: ${SECRETS_PATH_HOST}${DB_NAME_SECRET}
  db_user:
    file: ${SECRETS_PATH_HOST}${DB_USER_SECRET}
  db_pw_user:
    file: ${SECRETS_PATH_HOST}${DB_PW_USER_SECRET}
  db_pw_root:
    file: ${SECRETS_PATH_HOST}${DB_PW_ROOT_SECRET}
  wp_user:
    file: ${SECRETS_PATH_HOST}${WP_USER_SECRET}
  wp_pw_user:
    file: ${SECRETS_PATH_HOST}${WP_PW_USER_SECRET}
  wp_admin:
    file: ${SECRETS_PATH_HOST}${WP_ADMIN_SECRET}
  wp_pw_admin:
    file: ${SECRETS_PATH_HOST}${WP_PW_ADMIN_SECRET}
  wp_email_user:
    file: ${SECRETS_PATH_HOST}${WP_EMAIL_USER_SECRET}
  wp_email_admin:
    file: ${SECRETS_PATH_HOST}${WP_EMAIL_ADMIN_SECRET}

# ---------------------------------------------------------------------------- #

services:
  # https://hub.docker.com/_/nginx
  nginx:
    build:
      # Where the Dockerfile is located.
      context: ./requirements/nginx/
      # Dockerfile name *not required if already named 'Dockerfile'.
      dockerfile: Dockerfile
    # Custom name for the image being built.
    image: nginx:inception
    # Prevents that directory name be append to the service's name
    # (when executing 'docker-compose' without specifying -f <path>)
    secrets:
      - ${WP_EMAIL_ADMIN_SECRET}
    environment:
      - WP_DOMAIN_NAME=${WP_DOMAIN_NAME}
      - WP_EMAIL_ADMIN_FILE=${WP_EMAIL_ADMIN_FILE}
    container_name: nginx
    restart: on-failure:10
    # Allows HOST to communicate with container.
    ports:
      - "443:443"
    volumes:
      - volume-wordpress:/var/www/wp
    networks:
      inception:
        ipv4_address: ${NGINX_HOSTIP}

  # https://hub.docker.com/_/wordpress
  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress:inception
    secrets:
      - ${DB_NAME_SECRET}
      - ${DB_USER_SECRET}
      - ${DB_PW_USER_SECRET}
      - ${WP_USER_SECRET}
      - ${WP_PW_USER_SECRET}
      - ${WP_ADMIN_SECRET}
      - ${WP_PW_ADMIN_SECRET}
      - ${WP_EMAIL_USER_SECRET}
      - ${WP_EMAIL_ADMIN_SECRET}
    environment:
      - DB_NAME_FILE=${DB_NAME_FILE}
      - DB_USER_FILE=${DB_USER_FILE}
      - DB_PW_USER_FILE=${DB_PW_USER_FILE}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - WP_CONFIG_FILE_PATH=${WP_CONFIG_FILE_PATH}
      - WP_USER_FILE=${WP_USER_FILE}
      - WP_PW_USER_FILE=${WP_PW_USER_FILE}
      - WP_ADMIN_FILE=${WP_ADMIN_FILE}
      - WP_PW_ADMIN_FILE=${WP_PW_ADMIN_FILE}
      - WP_DOMAIN_NAME=${WP_DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_EMAIL_USER_FILE=${WP_EMAIL_USER_FILE}
      - WP_EMAIL_ADMIN_FILE=${WP_EMAIL_ADMIN_FILE}
    container_name: wordpress
    restart: on-failure:10
    # Only allows inter-container communications. (Not with HOST)
    # Exposes ports from a service to other services in the same Docker network.
    expose:
      - "9000"
    volumes:
      - volume-wordpress:/var/www/wp
    networks:
      inception:
        ipv4_address: ${WP_HOSTIP}

  # https://hub.docker.com/_/mariadb
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb:inception
    secrets:
      - ${DB_NAME_SECRET}
      - ${DB_USER_SECRET}
      - ${DB_PW_USER_SECRET}
      - ${DB_PW_ROOT_SECRET}
    environment:
      - DB_NAME_FILE=${DB_NAME_FILE}
      - DB_USER_FILE=${DB_USER_FILE}
      - DB_PW_USER_FILE=${DB_PW_USER_FILE}
      - DB_PW_ROOT_FILE=${DB_PW_ROOT_FILE}
      - SECRETS_PATH=${SECRETS_PATH}
    container_name: mariadb
    restart: on-failure:10
    expose:
      - "3306"
    volumes:
      - volume-mariadb:/var/lib/mysql
    networks:
      inception:
        ipv4_address: ${DB_HOSTIP}
