CREATE DATABASE IF NOT EXISTS `DATABASE_NAME`;
CREATE USER IF NOT EXISTS `DATABASE_USER`@'192.168.42.3' IDENTIFIED BY `DATABASE_PASSWORD`;
GRANT ALL PRIVILEGES ON `DATABASE_NAME` TO `DATABASE_USER`@'192.168.42.3' IDENTIFIED BY 'DATABASE_PASSWORD' WITH GRANT OPTION;
ALTER USER root@'localhost' IDENTIFIED BY 'DATABASE_ROOT_PASSWORD';
FLUSH PRIVILEGES;
